# config/config.yaml
urls:
  login: "https://practicetestautomation.com/practice-test-login/"
  dashboard: "https://practicetestautomation.com/dashboard/"

credentials:
  username: "student"
  password: "Password123"

timeouts:
  implicit: 5
  explicit: 60

retries:
  step_retry: 3
  test_retry: 2

mobile:
  server: "http://127.0.0.1:4723/wd/hub"
  caps:
    platformName: "Android"
    deviceName: "emulator-5554"
    automationName: "UiAutomator2"
    appPackage: "com.hp.smart"
    appActivity: "com.hp.smart.MainActivity"
    noReset: true

app:
  name: "Agentra Automation"
